// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Paper struct {
	ID            string             `json:"id"`
	ContentHash   string             `json:"content_hash"`
	SourceType    string             `json:"source_type"`
	SourceRef     pgtype.Text        `json:"source_ref"`
	Status        string             `json:"status"`
	RawKey        string             `json:"raw_key"`
	SchemaVersion pgtype.Text        `json:"schema_version"`
	ResultKey     pgtype.Text        `json:"result_key"`
	Error         pgtype.Text        `json:"error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
