// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: papers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaper = `-- name: CreatePaper :one
INSERT INTO papers (id, content_hash, source_type, source_ref, raw_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, content_hash, source_type, source_ref, status, raw_key, schema_version, result_key, error, created_at, updated_at
`

type CreatePaperParams struct {
	ID          string      `json:"id"`
	ContentHash string      `json:"content_hash"`
	SourceType  string      `json:"source_type"`
	SourceRef   pgtype.Text `json:"source_ref"`
	RawKey      string      `json:"raw_key"`
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, createPaper,
		arg.ID,
		arg.ContentHash,
		arg.SourceType,
		arg.SourceRef,
		arg.RawKey,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SourceType,
		&i.SourceRef,
		&i.Status,
		&i.RawKey,
		&i.SchemaVersion,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaper = `-- name: GetPaper :one
SELECT id, content_hash, source_type, source_ref, status, raw_key, schema_version, result_key, error, created_at, updated_at FROM papers WHERE id = $1
`

func (q *Queries) GetPaper(ctx context.Context, id string) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaper, id)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SourceType,
		&i.SourceRef,
		&i.Status,
		&i.RawKey,
		&i.SchemaVersion,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaperByHash = `-- name: GetPaperByHash :one
SELECT id, content_hash, source_type, source_ref, status, raw_key, schema_version, result_key, error, created_at, updated_at FROM papers WHERE content_hash = $1
`

func (q *Queries) GetPaperByHash(ctx context.Context, contentHash string) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaperByHash, contentHash)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SourceType,
		&i.SourceRef,
		&i.Status,
		&i.RawKey,
		&i.SchemaVersion,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaperDone = `-- name: MarkPaperDone :exec
UPDATE papers
SET status = 'done', schema_version = $1, result_key = $2, error = NULL
WHERE id = $3
`

type MarkPaperDoneParams struct {
	SchemaVersion pgtype.Text `json:"schema_version"`
	ResultKey     pgtype.Text `json:"result_key"`
	ID            string      `json:"id"`
}

func (q *Queries) MarkPaperDone(ctx context.Context, arg MarkPaperDoneParams) error {
	_, err := q.db.Exec(ctx, markPaperDone, arg.SchemaVersion, arg.ResultKey, arg.ID)
	return err
}

const markPaperFailed = `-- name: MarkPaperFailed :exec
UPDATE papers
SET status = 'failed', error = $1
WHERE id = $2
`

type MarkPaperFailedParams struct {
	Error pgtype.Text `json:"error"`
	ID    string      `json:"id"`
}

func (q *Queries) MarkPaperFailed(ctx context.Context, arg MarkPaperFailedParams) error {
	_, err := q.db.Exec(ctx, markPaperFailed, arg.Error, arg.ID)
	return err
}

const markPaperRunning = `-- name: MarkPaperRunning :exec
UPDATE papers SET status = 'running' WHERE id = $1
`

func (q *Queries) MarkPaperRunning(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markPaperRunning, id)
	return err
}
